upstream tileserv {
    server pg_tileserv:7800;
}

upstream api {
    server api:8010;
}

server {
    listen 80;

    location /tiles/ {
        proxy_pass http://tileserv/;
        proxy_set_header Host $host;
        add_header Cache-Control "public, max-age=3600";
    }

    location /api/ {
        proxy_pass http://api/api/;
        proxy_set_header Host $host;
    }
}
