-- Recria hierarquia User → Empresa → Obra → Furo → SPT (substitui modelo anterior).

PRAGMA foreign_keys=OFF;

DROP TABLE IF EXISTS "SPTLog";
DROP TABLE IF EXISTS "Borehole";
DROP TABLE IF EXISTS "Camada";
DROP TABLE IF EXISTS "SPT";
DROP TABLE IF EXISTS "Furo";
DROP TABLE IF EXISTS "Obra";

PRAGMA foreign_keys=ON;

CREATE TABLE "User" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "email" TEXT NOT NULL,
    "password" TEXT NOT NULL
);

CREATE UNIQUE INDEX "User_email_key" ON "User"("email");

CREATE TABLE "Empresa" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "nome" TEXT NOT NULL,
    "userId" INTEGER NOT NULL,
    CONSTRAINT "Empresa_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE "Obra" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "nome" TEXT NOT NULL,
    "cliente" TEXT NOT NULL,
    "local" TEXT NOT NULL,
    "empresaId" INTEGER NOT NULL,
    CONSTRAINT "Obra_empresaId_fkey" FOREIGN KEY ("empresaId") REFERENCES "Empresa" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE "Furo" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "codigo" TEXT NOT NULL,
    "obraId" INTEGER NOT NULL,
    CONSTRAINT "Furo_obraId_fkey" FOREIGN KEY ("obraId") REFERENCES "Obra" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE "SPT" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "prof" REAL NOT NULL,
    "g1" INTEGER NOT NULL,
    "g2" INTEGER NOT NULL,
    "g3" INTEGER NOT NULL,
    "solo" TEXT NOT NULL,
    "furoId" INTEGER NOT NULL,
    CONSTRAINT "SPT_furoId_fkey" FOREIGN KEY ("furoId") REFERENCES "Furo" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);
